= A Cover Letter for the Consideration of Jonathan Thiessen for the Position of Software Engineer - Infrastructure at Arista
Jonathan J. Thiessen <cv.enquiries@alonzo.church>
:notitle:
:noheader:
:github: https://github.com/jjthiessen
:gitlab: https://gitlab.com/tangential
:tel: +1.250.870.1096

[cols="<,>",frame=none,grid=none]
|===
|{docdate}

Attn: Hiring Manager +
Arista Networks +
|{author} +
mailto:{email}[{email}] +
link:tel:{tel}[{tel}] +
|===

Salutations,

I recently became aware of your posting for the position of _Software Engineer - Infrastructure_ (from Gabriel Gonzalez's https://twitter.com/GabrielG439/status/1402033436638945280[tweet concerning the posting]).
I have long wanted to apply my interests in both declarative configuration management and functional programming to a greater extent through my employment.
I feel as though this would be an ideal position for myself, and I hope you feel that I would be an ideal candidate for this position.

I presently work remotely (since 2016) with a very small and dynamic team in a highly collaborative manner on a semi-asynchronous basis.
We all teach and learn from each other.
There are many hats, and we share them all (not literally, of course).

I first encountered Haskell (and functional programming in general) while studying at the University of Waterloo.
The shift in perspective was both mind-bending and refreshing.
I decided to learn Haskell by using it for any programming assignment that didn't mandate a particular language.
This led to a particularly fun (and at times stressful) week of reading through http://learnyouahaskell.com[Learn You a Haskell for Great Good!] and implementing a Bayesian classifier.

After university, I got a job as a junior NOC technician at RackForce Networks (later acquired by https://terago.ca[TeraGo Networks]).
I worked my way up through the NOC, then I moved laterally to the development department, and worked my way up there.
I have (co)led several operational improvement initiatives including the proper adoption of version control, the authoring of a change management policy for development, the use of Puppet for managing all of our team's VMs, the adoption of most of the HashiCorp stack, and the use of GitLab's CI/CD pipelines.

I have been running NixOS as my sole desktop/workstation OS since late 2019.
I have written derivations for some additional versions of PHP in an attempt to determine the feasibility of building our application container images with Nix.

I have recently started working through https://haskellbook.com[Haskell Programming From First Principles].

My career has followed my more developed technical skills (network administration, system administration, and PHP development).
I am ready for a change and a challenge, and I would like to build upon my interest and fledgling skills in both Nix/NixOS and Haskell on a full-time basis.

Thank you for your time and consideration, +
— {author}
